version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/work
    command: sleep infinity

  client1:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/work
    command: sleep infinity

  client2:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/work
    command: sleep infinity